---
title: "Kidney"
author: "Otmane EL ALOI"
date: "11/03/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(mltools)
library(data.table)
library(survival)
library(evd)
```

# Présentation du projet:

### Présentation des données:

```{r data }
#One hot encoding categorical variables 
data<-kidney
data<- one_hot(as.data.table(kidney),cols="disease")
#Adding a column indicating if it's the first or second occurence of the disease
data$is_first<-rep(c(1,0),38)
#Making the data looks like given in the project 
data1<-data%>%
  filter(is_first==1)%>%
  select(-c("id","is_first","frail"))
data2<-data%>%
  filter(is_first==0)%>%
  select(c('time','status','age'))%>%
  rename("time_2"="time","age_2"="age","status_2"="status")
data <-cbind(data1,data2)
data$sex<-data$sex-1
#Readable order 
data<-data[,c(1,9,2,10,3,11,4,5,6,7,8)]
View(data)
```

### Code:

```{r MCMC}
MHWeibull_REffect <- function(data,iter = 10^5,
                              prop.sd = c(0.8,0.01,0.6,0.6,0.6,0.5,0.4,1)){
  
  time1 <-data$time
  time2<-data$time_2
  cens1 <- data$status
  cens2 <-data$status_2
  age1<-data$age
  age2<-data$age_2
  sex<-data$sex
  d1<-data$disease_GN
  d2<-data$disease_AN
  d3<-data$disease_PKD
  ## Define a "suitable" initial state for the chain
  init <- c(0,0,0,0,0,0,1,1, rep(1,38))
  acc.rates <- rep(0, 8+38)
  chain <- matrix(0, iter + 1, 8+38)
  colnames(chain) <- c("alpha", "beta_age", "beta_sex", "beta1", "beta_2","beta3", "tau", "r", paste("b", 1:38, sep =""))
  chain[1,] <- init
  
  for (i in 1:iter){
    
    current <- chain[i,]
    #Modifying alpha, beta_age,beta_sex,beta_1,beta_2,beta_3
    for (j in 1:6){
      prop<-current
      #Proposition
      prop[j]<-rnorm(1,current[j],prop.sd[j])

      #The top 
      scale1=exp(-(prop[1]+prop[2]*age1+prop[3]*sex+prop[4]*d1+prop[5]*d2+prop[6]*d3+prop[9:46]))
      scale2=exp(-(prop[1]+prop[2]*age2+prop[3]*sex+prop[4]*d1+prop[5]*d2+prop[6]*d3+prop[9:46]))  
      shape=rep(prop[8],38)

      top <- dnorm(prop[j],0,100, log = TRUE) + sum(cens1*dweibull(time1,shape=shape,scale=scale1, log=TRUE))+sum(cens2*dweibull(time2,shape=shape,scale=scale2, log=TRUE))+sum((1-cens1)*pweibull(time1,shape=shape,scale=scale1, log=TRUE, lower.tail = FALSE))+sum((1-cens2)*pweibull(time2,shape=shape,scale=scale2, log=TRUE, lower.tail = FALSE))
      
      #The bottom
    scale1=exp(-(current[1]+current[2]*age1+current[3]*sex+current[4]*d1+current[5]*d2+current[6]*d3+current[9:46]))
    scale2=exp(-(current[1]+current[2]*age2+current[3]*sex+current[4]*d1+current[5]*d2+current[6]*d3+current[9:46]))
      shape=rep(current[8],38)
      
      bottom <- dnorm(current[j],0,100, log = TRUE) + sum(cens1*dweibull(time1,shape=shape,scale=scale1, log=TRUE))+sum(cens2*dweibull(time2,shape=shape,scale=scale2, log=TRUE))+sum((1-cens1)*pweibull(time1,shape=shape,scale=scale1, log=TRUE, lower.tail = FALSE))+sum((1-cens2)*pweibull(time2,shape=shape,scale=scale2, log=TRUE, lower.tail = FALSE))
      alpha1 <- exp(top-bottom)
      if (runif(1) < alpha1){
        current[j] <- prop[j]
        acc.rates[j] <- acc.rates[j] + 1
      }
    }

    #Modfifying tau (conjugate prior)
    current[7] <-rgamma(1,shape=10^(-3)+38/2, rate=10^(-3)+sum(current[9:46]^2)/2)
    
    
    #Modfifying r
    
    #Proposition
    prop[8]<-rlnorm(1,log(current[8]),prop.sd[7])
    kernel.ratio<-(prop[8]/current[8])
    #The top 
      scale1=exp(-(prop[1]+prop[2]*age1+prop[3]*sex+prop[4]*d1+prop[5]*d2+prop[6]*d3+prop[9:46]))
      scale2=exp(-(prop[1]+prop[2]*age2+prop[3]*sex+prop[4]*d1+prop[5]*d2+prop[6]*d3+prop[9:46]))  
    shape=rep(prop[8],38)
    
    top <- dgamma(prop[8],1,10^(-3), log = TRUE) + sum(cens1*dweibull(time1,shape=shape,scale=scale1, log=TRUE))+sum(cens2*dweibull(time2,shape=shape,scale=scale2, log=TRUE))+sum((1-cens1)*pweibull(time1,shape=shape,scale=scale1, log=TRUE, lower.tail = FALSE))+sum((1-cens2)*pweibull(time2,shape=shape,scale=scale2, log=TRUE, lower.tail = FALSE))
    
    #The bottom
    scale1=exp(-(current[1]+current[2]*age1+current[3]*sex+current[4]*d1+current[5]*d2+current[6]*d3+current[9:46]))
    scale2=exp(-(current[1]+current[2]*age2+current[3]*sex+current[4]*d1+current[5]*d2+current[6]*d3+current[9:46]))
    shape=rep(current[8],38)
    
    bottom <- dgamma(current[8],shape=1,rate=10^(-3), log = TRUE) + sum(cens1*dweibull(time1,shape=shape,scale=scale1, log=TRUE))+sum(cens2*dweibull(time2,shape=shape,scale=scale2, log=TRUE))+sum((1-cens1)*pweibull(time1,shape=shape,scale=scale1, log=TRUE, lower.tail = FALSE))+sum((1-cens2)*pweibull(time2,shape=shape,scale=scale2, log=TRUE, lower.tail = FALSE))
  
    alpha2<- exp(top-bottom)*kernel.ratio
  
    if (runif(1) < alpha2){
      current[8] <- prop[8]
      acc.rates[8] <- acc.rates[8] + 1
    }
  
    #Modifying bi (on s'intéresse seulement au patient i)
    for (j in 9:46){
      
      ## On tire selon sigma de l'énoncé sinon notre chaîne devient instable
      current[j]<-rnorm(1,0,0.6367)
      
      #prop<-current
      #Proposition
      #prop[j]<-rnorm(1,current[j],prop.sd[8])
      
        #The top 
       #scale1=exp(prop[1]+prop[2]*age1[j-8]+prop[3]*sex[j-8]+prop[4]*d1[j-8]+prop[5]*d2[j-8]+prop[6]*d3[j-8]+prop[j])
       #scale2=exp(prop[1]+prop[2]*age2[j-8]+prop[3]*sex[j-8]+prop[4]*d1[j-8]+prop[5]*d2[j-8]+prop[6]*d3[j-8]+prop[j])   
       #shape=rep(prop[8],2)
       
       #top <- dnorm(prop[j],0,1/sqrt(current[7]), log = TRUE) + sum(cens1[j-8]*dweibull(time1[j-8],shape=shape,scale=scale1, log=TRUE))+sum(cens2[j-8]*dweibull(time2[j-8],shape=shape,scale=scale2, log=TRUE))+sum((1-cens1[j-8])*pweibull(time1[j-8],shape=shape,scale=scale1, log=TRUE, lower.tail = FALSE))+sum((1-cens2[j-8])*pweibull(time2[j-8],shape=shape,scale=scale2, log=TRUE, lower.tail = FALSE))
       
       #The bottom
       #scale1=exp(current[1]+current[2]*age1[j-8]+current[3]*sex[j-8]+current[4]*d1[j-8]+current[5]*d2[j-8]+current[6]*d3[j-8]+current[j])
       #scale2=exp(current[1]+current[2]*age2[j-8]+current[3]*sex[j-8]+current[4]*d1[j-8]+current[5]*d2[j-8]+current[6]*d3[j-8]+current[j])
       #shape=rep(current[8],2)
       
       #bottom <- dnorm(prop[j],0,1/sqrt(current[7]), log = TRUE) +  sum(cens1[j-8]*dweibull(time1[j-8],shape=shape,scale=scale1, log=TRUE))+sum(cens2[j-8]*dweibull(time2[j-8],shape=shape,scale=scale2, log=TRUE))+sum((1-cens1[j-8])*pweibull(time1[j-8],shape=shape,scale=scale1, log=TRUE, lower.tail = FALSE))+sum((1-cens2[j-8])*pweibull(time2[j-8],shape=shape,scale=scale2, log=TRUE, lower.tail = FALSE))
       
       #alpha3 <- exp(top-bottom)
       #if (runif(1) < alpha3){
        # current[j] <- prop[j]
        # acc.rates[j] <- acc.rates[j] + 1
       #}
            
    }
    
    chain[i+1,] <- current
  }
  return(list(chain = chain, acc.rates = acc.rates / iter))
}
```

```{r result}
out <- MHWeibull_REffect(data)
```

```{r }
#le taux d'acceaptation
out$acc.rates[1:8]

#dropping burning period
out$chain<- out$chain[-(1:1500),]
```

```{r}
#Plotting the chain 
expression<- c("alpha", "beta_age", "beta_sex", "beta1", "beta_2","beta3", "tau", "r")
#plot
for (j in 1:8)
  plot(out$chain[,j], type = "l", ylab = expression[j])
```


```{r}
#Posterior  main estimation 
theta_hat <-colMeans(out$chain)

print(theta_hat[1:8])
```

```{r}
#Run in console:
expression<- c("alpha", "beta_age", "beta_sex", "beta1", "beta2","beta3", "tau", "r")
par(mfrow = c(8, 2),mar = c(4, 5, 0.5, 0.5))
#plot
for (j in 1:8){
  plot(out$chain[,j], type = "l", main = "",ylab=expression[j])
  plot(density(out$chain[,j]), type = "l", main = "")
}
```
